# Site settings
title: Prateep Gedupudi
header-img: img/home-bg.jpg
email: prateep.gedupudi@gmail.com
description: "A self motivated person by taking inspirations from movies, music, technology, and from colleagues. An active team player committed to progress, innovation and excellence with strong ownership, problem solving, and project, time management skills. Positive attitude to challenges, and result-oriented."
baseurl: ""
url: "http://prateep.info"
twitter_username: prateepgedupudi
github_username:  prateepgedupudi
facebook_username:  prateep.gedupudi
youtube_username: PrateepGedupudi
linkedin_username: prateepgedupudi

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: ["jekyll-paginate"]
